version: 29.3.1

services:
  postgres:
    image: postgres:17
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8000:8000
    command: npm run dev

volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt